services:
    cdwv.database_dumper.file_name_builder:
        class: CodeWave\DatabaseDumperCommandBundle\FileSystem\FileNameBuilder

    cdwv.database_dumper.dumper_command_builder.postgresql:
        class: CodeWave\DatabaseDumperCommandBundle\CommandBuilder\PgsqlDumpCommandBuilder
        arguments:
            - "@cdwv.database_dumper.file_name_builder"

    cdwv.database_dumper.dumper_command_builder.mysql:
        class: CodeWave\DatabaseDumperCommandBundle\CommandBuilder\MysqlDumpCommandBuilder
        arguments:
            - "@cdwv.database_dumper.file_name_builder"

    cdwv.database_dumper.dumper_command_builder.sqlite:
        class: CodeWave\DatabaseDumperCommandBundle\CommandBuilder\Sqlite3CommandBuilder
        arguments:
            - "@cdwv.database_dumper.file_name_builder"

    cdwv.database_dumper.dumper_command_builder.provider:
        class: CodeWave\DatabaseDumperCommandBundle\CommandBuilder\DumpCommandBuilderProvider
        arguments:
            - "@service_container"

