dist: trusty
sudo: required

language: php

php:
  - 5.5
  - 5.6
  - 7.0

addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

services:
  - mysql
  - postgresql

before_install:
  - mysql -e 'CREATE DATABASE dodump;'
  - psql -c 'create database dodump;' -U postgres
  - composer install

script:
- ./vendor/bin/phpunit --configuration phpunit.xml.dist