dist: trusty
sudo: required

language: php

php:
  - 5.5
  - 5.6
  - 7.0

addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

services:
  - mysql

before_install:
  - composer install

script:
- ./vendor/bin/phpunit --configuration phpunit.xml.dist